/**
 * Admin Console Component
 * =======================
 *
 * Main admin interface for monitoring and moderating LLM conversations.
 * Provides a split-panel layout with a filterable conversation list on the
 * left and a detailed message inspector on the right.
 *
 * Features:
 * - Filter conversations by user, section, script, date range, and search text
 * - Paginated conversation list with type badges and status indicators
 * - Full message history with raw response / context / payload inspection
 * - Moderation actions: block, unblock, delete conversations
 * - Context and payload popups for debugging API interactions
 *
 * Data is loaded via the `adminApi` utility which calls the
 * ModuleLlmAdminConsoleController PHP backend.
 *
 * @module components/admin/AdminConsole
 */

import React, { useEffect, useMemo, useRef, useState } from 'react';
import { Container, Row, Col, Card, Form, Button, Badge, Alert, Spinner, Pagination, Modal } from 'react-bootstrap';
import Select from 'react-select';
import { adminApi } from '../../utils/api';
import { formatDateTime } from '../../utils/formatters';
import { ContextPopup } from './ContextPopup';
import { PayloadPopup } from './PayloadPopup';
import { AdminMessageList } from './AdminMessageList';
import { AdminConversationsPanel } from './AdminConversationsPanel';
import { AdminConversationDetailHeader } from './AdminConversationDetailHeader';
import { compactSelectStyles } from './selectStyles';
import type { AdminConfig, AdminConversation, Message } from '../../types';
import { getConversationTypeMeta } from './conversationTypes';
import './AdminConsole.css';

/** Active filter state for the conversation list. */
interface AdminFilters {
  userId: string;
  sectionId: string;
  scriptId: string;
  query: string;
  dateFrom: string;
  dateTo: string;
}

// Confirmation modal state interface
interface ConfirmationModal {
  show: boolean;
  title: string;
  message: string;
  confirmText: string;
  confirmVariant: 'danger' | 'warning' | 'success' | 'primary';
  onConfirm: () => void;
}

interface FilterOption {
  id: number;
  name: string;
  email?: string;
  user_validation_code?: string | null;
}

// Helper function to get today's date in YYYY-MM-DD format
const getTodayDate = (): string => {
  const today = new Date();
  return today.toISOString().split('T')[0];
};

/** AdminConsole component. */
export const AdminConsole: React.FC<{ config: AdminConfig }> = ({ config }) => {
  const [filters, setFilters] = useState<AdminFilters>({ 
    userId: '', 
    sectionId: '', 
    scriptId: '',
    query: '',
    dateFrom: getTodayDate(),
    dateTo: getTodayDate()
  });
  const [filterOptions, setFilterOptions] = useState<{
    users: FilterOption[];
    sections: { id: number; name: string }[];
    scripts: { id: number; name: string }[];
  }>({ users: [], sections: [], scripts: [] });
  const [conversations, setConversations] = useState<AdminConversation[]>([]);
  const [selectedConversation, setSelectedConversation] = useState<AdminConversation | null>(null);
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalConversations, setTotalConversations] = useState(0);
  const [showFilters, setShowFilters] = useState(true);
  const [includeAutogenerated, setIncludeAutogenerated] = useState(false);
  const [contextPopup, setContextPopup] = useState<{
    show: boolean;
    message: Message | null;
    target: HTMLElement | null;
  }>({ show: false, message: null, target: null });

  // Payload popup state (for viewing API request payload)
  const [payloadPopup, setPayloadPopup] = useState<{
    show: boolean;
    message: Message | null;
  }>({ show: false, message: null });

  // Confirmation modal state
  const [confirmModal, setConfirmModal] = useState<ConfirmationModal>({
    show: false,
    title: '',
    message: '',
    confirmText: 'Confirm',
    confirmVariant: 'primary',
    onConfirm: () => {}
  });

  // Block reason input state
  const [blockReason, setBlockReason] = useState('');
  const stickyTopRef = useRef<HTMLDivElement>(null);
  const [stickyTopHeight, setStickyTopHeight] = useState(0);

  const restorePageScroll = (scrollTop: number) => {
    window.requestAnimationFrame(() => {
      window.scrollTo({ top: scrollTop, behavior: 'auto' });
      window.setTimeout(() => {
        window.scrollTo({ top: scrollTop, behavior: 'auto' });
      }, 0);
    });
  };

  useEffect(() => {
    loadFilterOptions();
  }, []);

  useEffect(() => {
    const updateStickyTopHeight = () => {
      setStickyTopHeight(stickyTopRef.current?.offsetHeight ?? 0);
    };

    updateStickyTopHeight();
    window.addEventListener('resize', updateStickyTopHeight);
    return () => window.removeEventListener('resize', updateStickyTopHeight);
  }, []);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      setStickyTopHeight(stickyTopRef.current?.offsetHeight ?? 0);
    }, 0);

    return () => window.clearTimeout(timer);
  }, [showFilters, error, totalConversations, conversations.length, includeAutogenerated]);

  useEffect(() => {
    loadConversations(1);
  }, [filters]);

  const filteredConversations = useMemo(() => (
    conversations.filter((conversation) => includeAutogenerated || !getConversationTypeMeta(conversation).autogenerated)
  ), [conversations, includeAutogenerated]);

  const hiddenAutogeneratedCount = useMemo(() => (
    conversations.reduce((total, conversation) => total + (getConversationTypeMeta(conversation).autogenerated ? 1 : 0), 0)
  ), [conversations]);

  // Handle conversation ID from URL on initial load
  useEffect(() => {
    const url = new URL(window.location.href);
    const conversationId = url.searchParams.get('conversation');
    if (conversationId && conversations.length > 0) {
      const sourceList = includeAutogenerated
        ? conversations
        : conversations.filter((conversation) => !getConversationTypeMeta(conversation).autogenerated);
      const conversation = sourceList.find(c => c.id.toString() === conversationId);
      if (conversation && (!selectedConversation || selectedConversation.id.toString() !== conversationId)) {
        selectConversation(conversation);
      }
    }
  }, [conversations, includeAutogenerated]); // Re-run when conversations are loaded

  useEffect(() => {
    if (includeAutogenerated || !selectedConversation) {
      return;
    }

    if (!getConversationTypeMeta(selectedConversation).autogenerated) {
      return;
    }

    setSelectedConversation(null);
    setMessages([]);
    const url = new URL(window.location.href);
    url.searchParams.delete('conversation');
    window.history.replaceState({}, '', url.toString());
  }, [includeAutogenerated, selectedConversation]);

  // Handle browser back/forward navigation
  useEffect(() => {
    const handlePopState = (event: PopStateEvent) => {
      const url = new URL(window.location.href);
      const conversationId = url.searchParams.get('conversation');
      
      if (conversationId) {
        const conversation = conversations.find(c => c.id.toString() === conversationId);
        if (conversation) {
          // Don't update URL again since we're responding to URL change
          selectConversation(conversation, { updateUrl: false })
            .catch(err => {
              setError((err as Error).message);
            });
        }
      } else {
        // No conversation in URL, clear selection
        setSelectedConversation(null);
        setMessages([]);
      }
    };

    window.addEventListener('popstate', handlePopState);
    return () => window.removeEventListener('popstate', handlePopState);
  }, [conversations]);

  const loadFilterOptions = async () => {
    try {
      const response = await adminApi.getFilters();
      setFilterOptions(response.filters);
    } catch (err) {
      setError((err as Error).message);
    }
  };

  const loadConversations = async (page: number = currentPage, options?: { showLoading?: boolean }) => {
    const shouldShowLoading = options?.showLoading !== false;
    if (shouldShowLoading) {
      setLoading(true);
    }
    setError(null);

    try {
      const response = await adminApi.getConversations({
        page,
        per_page: config.pageSize,
        user_id: filters.userId || undefined,
        section_id: filters.sectionId || undefined,
        script_id: filters.scriptId || undefined,
        q: filters.query || undefined,
        date_from: filters.dateFrom || undefined,
        date_to: filters.dateTo || undefined
      });

      setConversations(response.items || []);
      setCurrentPage(response.page || page);
      setTotalPages(Math.ceil((response.total || 0) / config.pageSize));
      setTotalConversations(response.total || 0);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      if (shouldShowLoading) {
        setLoading(false);
      }
    }
  };

  const selectConversation = async (
    conversation: AdminConversation,
    options?: { showLoading?: boolean; updateUrl?: boolean; updateSelection?: boolean }
  ) => {
    const shouldShowLoading = options?.showLoading !== false;
    const shouldUpdateUrl = options?.updateUrl !== false;
    const shouldUpdateSelection = options?.updateSelection !== false;

    if (shouldUpdateSelection) {
      setSelectedConversation(conversation);
    }

    if (shouldUpdateUrl) {
      const url = new URL(window.location.href);
      url.searchParams.set('conversation', conversation.id.toString());
      window.history.pushState({ conversationId: conversation.id }, '', url.toString());
    }

    if (shouldShowLoading) {
      setLoading(true);
    }

    try {
      const response = await adminApi.getMessages(conversation.id.toString());
      setMessages(response.messages || []);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      if (shouldShowLoading) {
        setLoading(false);
      }
    }
  };

  const handleFilterChange = (filterType: keyof AdminFilters, value: string) => {
    setFilters(prev => ({ ...prev, [filterType]: value }));
    setSelectedConversation(null);
    setMessages([]);
    setCurrentPage(1);
  };

  const clearFilters = () => {
    setFilters({ 
      userId: '', 
      sectionId: '', 
      scriptId: '',
      query: '',
      dateFrom: getTodayDate(),
      dateTo: getTodayDate()
    });
    setSelectedConversation(null);
    setMessages([]);
    setCurrentPage(1);
  };

  const handleRefresh = async () => {
    const scrollTop = window.scrollY || window.pageYOffset || 0;
    setRefreshing(true);
    try {
      await loadConversations(currentPage, { showLoading: false });
      if (selectedConversation) {
        await selectConversation(selectedConversation, {
          showLoading: false,
          updateUrl: false,
          updateSelection: false,
        });
      }
      restorePageScroll(scrollTop);
    } finally {
      setRefreshing(false);
    }
  };

  // ========== Admin Action Handlers ==========

  // Helper to show confirmation modal
  const showConfirmation = (
    title: string,
    message: string,
    confirmText: string,
    confirmVariant: 'danger' | 'warning' | 'success' | 'primary',
    onConfirm: () => void
  ) => {
    setConfirmModal({
      show: true,
      title,
      message,
      confirmText,
      confirmVariant,
      onConfirm
    });
  };

  // Helper to hide confirmation modal
  const hideConfirmation = () => {
    setConfirmModal(prev => ({ ...prev, show: false }));
    setBlockReason('');
  };

  const handleDeleteConversation = (conversationId: string) => {
    showConfirmation(
      'Delete Conversation',
      'Are you sure you want to delete this conversation? The conversation will be hidden from the user but kept in the database for audit purposes.',
      'Delete',
      'danger',
      async () => {
        hideConfirmation();
        setLoading(true);
        try {
          const response = await adminApi.deleteConversation(conversationId);
          if (response.error) {
            throw new Error(response.error);
          }
          
          // Clear selection and refresh list
          setSelectedConversation(null);
          setMessages([]);
          await loadConversations(currentPage);
        } catch (err) {
          setError((err as Error).message);
        } finally {
          setLoading(false);
        }
      }
    );
  };

  const handleBlockConversation = (conversationId: string) => {
    // Show block modal with reason input
    setConfirmModal({
      show: true,
      title: 'Block Conversation',
      message: 'The user will not be able to continue this conversation. Optionally enter a reason for blocking:',
      confirmText: 'Block',
      confirmVariant: 'warning',
      onConfirm: async () => {
        hideConfirmation();
        setLoading(true);
        try {
          const response = await adminApi.blockConversation(conversationId, blockReason || undefined);
          if (response.error) {
            throw new Error(response.error);
          }
          
          // Update the selected conversation's blocked status
          if (selectedConversation && selectedConversation.id.toString() === conversationId) {
            setSelectedConversation({
              ...selectedConversation,
              blocked: true,
              blocked_reason: blockReason || 'Manually blocked by administrator'
            });
          }
          
          // Refresh conversation list
          await loadConversations(currentPage);
        } catch (err) {
          setError((err as Error).message);
        } finally {
          setLoading(false);
        }
      }
    });
  };

  const handleUnblockConversation = (conversationId: string) => {
    showConfirmation(
      'Unblock Conversation',
      'Are you sure you want to unblock this conversation? The user will be able to continue chatting.',
      'Unblock',
      'success',
      async () => {
        hideConfirmation();
        setLoading(true);
        try {
          const response = await adminApi.unblockConversation(conversationId);
          if (response.error) {
            throw new Error(response.error);
          }
          
          // Update the selected conversation's blocked status
          if (selectedConversation && selectedConversation.id.toString() === conversationId) {
            setSelectedConversation({
              ...selectedConversation,
              blocked: false,
              blocked_reason: undefined
            });
          }
          
          // Refresh conversation list
          await loadConversations(currentPage);
        } catch (err) {
          setError((err as Error).message);
        } finally {
          setLoading(false);
        }
      }
    );
  };

  // ========== End Admin Action Handlers ==========

  const getUserDisplayName = (user: FilterOption) => {
    const nameParts = [];
    if (user.name) nameParts.push(user.name);
    if (user.email) nameParts.push(`(${user.email})`);
    if (user.user_validation_code) nameParts.push(`[ ${user.user_validation_code}]`);

    return nameParts.length > 0 ? nameParts.join(' ') : `User ${user.id}`;
  };

  const hasActiveFilters = filters.dateFrom || filters.dateTo || filters.userId || filters.sectionId || filters.scriptId || filters.query;

  // Prepare options for react-select
  const userOptions = [
    { value: '', label: 'All users' },
    ...filterOptions.users.map(user => ({
      value: user.id.toString(),
      label: getUserDisplayName(user)
    }))
  ];

  const sectionOptions = [
    { value: '', label: 'All sections' },
    ...filterOptions.sections.map(section => ({
      value: section.id.toString(),
      label: section.name
    }))
  ];

  const scriptOptions = [
    { value: '', label: 'All scripts' },
    ...(filterOptions.scripts || []).map(script => ({
      value: script.id.toString(),
      label: script.name
    }))
  ];

  const selectedConversationMeta = selectedConversation ? getConversationTypeMeta(selectedConversation) : null;

  return (
    <Container fluid className="llm-admin-console py-2">
      <div ref={stickyTopRef} className="admin-top-sticky mb-3">
        {/* Header Section */}
        <Row className="mb-3">
          <Col>
            <div className="d-flex justify-content-between align-items-center flex-wrap admin-header">
              <div className="d-flex align-items-center flex-wrap admin-header-title">
                <h4 className="text-dark mb-0 font-weight-bold">
                  <i className="fas fa-comments mr-2 text-secondary"></i>
                  {config.labels.heading}
                </h4>
                <Badge variant="secondary" className="ml-2">
                  {totalConversations.toLocaleString()} conversations
                </Badge>
                {hasActiveFilters && (
                  <Badge variant="info" className="ml-2">
                    {filteredConversations.length} visible
                  </Badge>
                )}
              </div>
              <div className="admin-header-buttons">
                <Button
                  size="sm"
                  variant={showFilters ? 'secondary' : 'outline-secondary'}
                  onClick={() => setShowFilters(!showFilters)}
                >
                  <i className="fas fa-filter"></i>
                  <span className="d-none d-sm-inline">{showFilters ? 'Hide' : 'Show'}</span>
                  <span className="d-sm-none">{showFilters ? 'Hide' : 'Filters'}</span>
                </Button>
              <Button
                size="sm"
                variant="primary"
                onClick={handleRefresh}
                disabled={loading || refreshing}
              >
                  <i className={`fas fa-sync-alt ${refreshing ? 'fa-spin' : ''}`}></i>
                  <span className="d-none d-sm-inline">Refresh</span>
                </Button>
                <Button
                  size="sm"
                  variant="outline-danger"
                  onClick={clearFilters}
                  disabled={!hasActiveFilters}
                >
                  <i className="fas fa-times"></i>
                  <span className="d-none d-sm-inline">Clear</span>
                </Button>
              </div>
            </div>
          </Col>
        </Row>

        {/* Error Alert */}
        {error && (
          <Row className="mb-3">
            <Col>
              <Alert variant="danger" dismissible onClose={() => setError(null)}>
                <i className="fas fa-exclamation-triangle mr-2"></i>
                {error}
              </Alert>
            </Col>
          </Row>
        )}

        {/* Filters Row - Collapsible */}
        {showFilters && (
          <Row className="mb-3">
            <Col>
              <Card className="border admin-filters-card">
                <Card.Body className="py-3">
                  <div className="filter-grid">
                  {/* Date Range Filter */}
                  <div className="filter-col filter-col-date">
                    <Form.Label className="small text-muted mb-1">
                      <i className="fas fa-calendar-alt mr-1"></i>
                      Date Range
                    </Form.Label>
                    <div className="date-range-inputs">
                      <Form.Control
                        type="date"
                        value={filters.dateFrom}
                        onChange={(e) => handleFilterChange('dateFrom', e.target.value)}
                        className="filter-input"
                      />
                      <Form.Control
                        type="date"
                        value={filters.dateTo}
                        onChange={(e) => handleFilterChange('dateTo', e.target.value)}
                        className="filter-input"
                      />
                    </div>
                  </div>

                  {/* User Filter */}
                  <div className="filter-col filter-col-half">
                    <Form.Label className="small text-muted mb-1">
                      <i className="fas fa-user mr-1"></i>
                      {config.labels.userFilterLabel}
                    </Form.Label>
                    <Select
                      value={userOptions.find(option => option.value === filters.userId)}
                      onChange={(selectedOption) => handleFilterChange('userId', selectedOption?.value || '')}
                      options={userOptions}
                      isSearchable={true}
                      isClearable={false}
                      placeholder="All users..."
                      className="react-select-container filter-select"
                      classNamePrefix="react-select"
                      menuPortalTarget={document.body}
                      styles={compactSelectStyles}
                    />
                  </div>

                  {/* Section Filter */}
                  <div className="filter-col filter-col-half">
                    <Form.Label className="small text-muted mb-1">
                      <i className="fas fa-folder mr-1"></i>
                      {config.labels.sectionFilterLabel}
                    </Form.Label>
                    <Select
                      value={sectionOptions.find(option => option.value === filters.sectionId)}
                      onChange={(selectedOption) => handleFilterChange('sectionId', selectedOption?.value || '')}
                      options={sectionOptions}
                      isSearchable={true}
                      isClearable={false}
                      placeholder="All sections..."
                      className="react-select-container filter-select"
                      classNamePrefix="react-select"
                      menuPortalTarget={document.body}
                      styles={compactSelectStyles}
                    />
                  </div>

                  {/* Script Filter */}
                  {scriptOptions.length > 1 && (
                    <div className="filter-col filter-col-half">
                      <Form.Label className="small text-muted mb-1">
                        <i className="fas fa-code mr-1"></i>
                        Script
                      </Form.Label>
                      <Select
                        value={scriptOptions.find(option => option.value === filters.scriptId)}
                        onChange={(selectedOption) => handleFilterChange('scriptId', selectedOption?.value || '')}
                        options={scriptOptions}
                        isSearchable={true}
                        isClearable={false}
                        placeholder="All scripts..."
                        className="react-select-container filter-select"
                        classNamePrefix="react-select"
                        menuPortalTarget={document.body}
                        styles={compactSelectStyles}
                      />
                    </div>
                  )}

                  {/* Search Filter */}
                  <div className="filter-col filter-col-half">
                    <Form.Label className="small text-muted mb-1">
                      <i className="fas fa-search mr-1"></i>
                      Search
                    </Form.Label>
                    <Form.Control
                      type="text"
                      placeholder={config.labels.searchPlaceholder}
                      value={filters.query}
                      onChange={(e) => handleFilterChange('query', e.target.value)}
                      className="filter-input"
                    />
                  </div>
                  </div>
                </Card.Body>
              </Card>
            </Col>
          </Row>
        )}
      </div>

      {/* Main Content: Conversations and Messages */}
      <Row className="admin-main-row">
        {/* Conversations List */}
        <Col lg={5} xl={4} className="mb-3 mb-lg-0 admin-panel-col admin-sticky-col">
          <div className="admin-sticky-sidebar" style={{ top: `${Math.max(stickyTopHeight + 8, 16)}px` }}>
            <AdminConversationsPanel
              conversations={filteredConversations}
              selectedConversation={selectedConversation}
              loading={loading}
              includeAutogenerated={includeAutogenerated}
              hiddenAutogeneratedCount={hiddenAutogeneratedCount}
              hasActiveFilters={!!hasActiveFilters}
              currentPage={currentPage}
              totalPages={totalPages}
              onToggleIncludeAutogenerated={setIncludeAutogenerated}
              onSelectConversation={selectConversation}
              onLoadPage={loadConversations}
              loadingLabel={config.labels.loadingLabel}
              emptyLabel={config.labels.conversationsEmpty}
            />
          </div>
        </Col>

        {/* Messages Panel */}
        <Col lg={7} xl={8} className="admin-panel-col">
          <Card className="border messages-panel h-100">
            {loading && selectedConversation ? (
              <Card.Body className="text-center py-5">
                <Spinner animation="border" variant="secondary" size="sm" className="mb-3" />
                <div className="text-muted">{config.labels.loadingLabel}</div>
              </Card.Body>
            ) : !selectedConversation ? (
              <Card.Body className="text-center py-5 d-flex flex-column justify-content-center">
                <i className="fas fa-hand-pointer fa-3x text-muted mb-3"></i>
                <h5 className="text-muted mb-2">{config.labels.messagesEmpty}</h5>
                <p className="text-muted small mb-0">Select a conversation to view its messages</p>
              </Card.Body>
            ) : (
              <>
                <Card.Header className="bg-light py-2">
                  {selectedConversationMeta && (
                    <AdminConversationDetailHeader
                      conversation={selectedConversation}
                      conversationMeta={selectedConversationMeta}
                      onBlockConversation={handleBlockConversation}
                      onUnblockConversation={handleUnblockConversation}
                      onDeleteConversation={handleDeleteConversation}
                    />
                  )}
                </Card.Header>

                <Card.Body className="messages-container p-3">
                  {messages.length === 0 ? (
                    <div className="text-center py-5">
                      <i className="fas fa-comment-slash fa-2x text-muted mb-3"></i>
                      <div className="text-muted">No messages in this conversation</div>
                    </div>
                  ) : (
                    <AdminMessageList messages={messages} formatDate={formatDateTime} setContextPopup={setContextPopup} setPayloadPopup={setPayloadPopup} />
                  )}
                </Card.Body>
              </>
            )}
          </Card>
        </Col>
      </Row>

      {/* Context Popup Modal */}
      {contextPopup.show && contextPopup.message && (
        <ContextPopup
          message={contextPopup.message}
          show={contextPopup.show}
          onHide={() => setContextPopup({ show: false, message: null, target: null })}
        />
      )}

      {/* Payload Popup Modal */}
      {payloadPopup.show && payloadPopup.message && (
        <PayloadPopup
          message={payloadPopup.message}
          show={payloadPopup.show}
          onHide={() => setPayloadPopup({ show: false, message: null })}
        />
      )}

      {/* Confirmation Modal */}
      <Modal show={confirmModal.show} onHide={hideConfirmation} centered>
        <Modal.Header closeButton>
          <Modal.Title>
            <i className={`fas ${confirmModal.confirmVariant === 'danger' ? 'fa-trash-alt' : confirmModal.confirmVariant === 'warning' ? 'fa-ban' : 'fa-check-circle'} mr-2 text-${confirmModal.confirmVariant}`}></i>
            {confirmModal.title}
          </Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p>{confirmModal.message}</p>
          {/* Show reason input for block action */}
          {confirmModal.title === 'Block Conversation' && (
            <Form.Group>
              <Form.Label className="small text-muted">Reason (optional)</Form.Label>
              <Form.Control
                type="text"
                placeholder="Enter reason for blocking..."
                value={blockReason}
                onChange={(e) => setBlockReason(e.target.value)}
              />
            </Form.Group>
          )}
        </Modal.Body>
        <Modal.Footer>
          <Button variant="secondary" onClick={hideConfirmation}>
            Cancel
          </Button>
          <Button variant={confirmModal.confirmVariant} onClick={confirmModal.onConfirm}>
            {confirmModal.confirmText}
          </Button>
        </Modal.Footer>
      </Modal>
    </Container>
  );
};
