/**
 * Paginated conversation list panel for the Admin Console.
 *
 * Renders a scrollable card list with type badges, date indicators,
 * and an auto-generated conversation toggle. Supports selection via
 * click and keyboard-driven pagination.
 *
 * @module components/admin/AdminConversationsPanel
 */
import React from 'react';
import { Badge, Card, Form, Pagination, Spinner } from 'react-bootstrap';
import type { AdminConversation } from '../../types';
import { formatConversationDateBadge, getConversationTypeMeta } from './conversationTypes';

interface AdminConversationsPanelProps {
  conversations: AdminConversation[];
  selectedConversation: AdminConversation | null;
  loading: boolean;
  includeAutogenerated: boolean;
  hiddenAutogeneratedCount: number;
  hasActiveFilters: boolean;
  currentPage: number;
  totalPages: number;
  onToggleIncludeAutogenerated: (checked: boolean) => void;
  onSelectConversation: (conversation: AdminConversation) => void;
  onLoadPage: (page: number) => void;
  loadingLabel: string;
  emptyLabel: string;
}

/** Panel component for admin conversations panel. */
export const AdminConversationsPanel: React.FC<AdminConversationsPanelProps> = ({
  conversations,
  selectedConversation,
  loading,
  includeAutogenerated,
  hiddenAutogeneratedCount,
  hasActiveFilters,
  currentPage,
  totalPages,
  onToggleIncludeAutogenerated,
  onSelectConversation,
  onLoadPage,
  loadingLabel,
  emptyLabel,
}) => {
  return (
    <Card className="border conversations-panel h-100">
      <Card.Header className="bg-secondary text-white py-2">
        <div className="d-flex justify-content-between align-items-center mb-2">
          <span className="font-weight-bold">
            <i className="fas fa-list mr-2"></i>
            Conversations
          </span>
          <Badge variant="light">
            {conversations.length}
          </Badge>
        </div>
        <div className="d-flex justify-content-between align-items-center flex-wrap conversations-toolbar">
          <div className="small text-white-50">
            Grouped by type. Real conversations shown by default.
          </div>
          <Form.Check
            id="include-autogenerated"
            type="checkbox"
            custom
            label="Include autogenerated"
            checked={includeAutogenerated}
            onChange={(event) => onToggleIncludeAutogenerated(event.target.checked)}
            className="small text-white mb-0 autogenerated-toggle"
          />
        </div>
      </Card.Header>

      <div className="conversations-list">
        {loading && conversations.length === 0 ? (
          <div className="text-center py-5">
            <Spinner animation="border" variant="secondary" className="mb-3" />
            <div className="text-muted">{loadingLabel}</div>
          </div>
        ) : conversations.length === 0 ? (
          <div className="text-center py-5 px-3">
            <i className="fas fa-inbox fa-3x text-muted mb-3"></i>
            <h6 className="text-muted mb-2">{emptyLabel}</h6>
            {!includeAutogenerated && hiddenAutogeneratedCount > 0 ? (
              <p className="text-muted small mb-0">
                {hiddenAutogeneratedCount} autogenerated conversation{hiddenAutogeneratedCount !== 1 ? 's are' : ' is'} hidden.
              </p>
            ) : hasActiveFilters ? (
              <p className="text-muted small mb-0">Try adjusting your filters</p>
            ) : null}
          </div>
        ) : (
          conversations.map((conversation) => {
            const conversationMeta = getConversationTypeMeta(conversation);
            return (
              <div
                key={conversation.id}
                className={`conversation-item conversation-item--${conversationMeta.key} p-3 border-bottom ${
                  selectedConversation?.id === conversation.id ? 'active' : ''
                }`}
                onClick={() => onSelectConversation(conversation)}
              >
                <div className="d-flex justify-content-between align-items-start mb-2">
                  <span className={conversationMeta.badgeClass}>
                    <i className={`fas ${conversationMeta.icon} mr-1`}></i>
                    {conversationMeta.label}
                  </span>
                  <Badge variant="light" className="conversation-date-badge ml-2 flex-shrink-0">
                    {formatConversationDateBadge(conversation.updated_at)}
                  </Badge>
                </div>

                <h6 className="font-weight-bold mb-1 conversation-title">
                  {conversationMeta.displayTitle}
                </h6>

                <div className="small conversation-user-line mb-2">
                  <i className="fas fa-user mr-1"></i>
                  {conversation.user_name || 'Unknown user'}
                </div>

                <div className="conversation-chip-row">
                  {conversation.section_name && (
                    <span className="conversation-chip">
                      <i className="fas fa-folder-open mr-1"></i>
                      {conversation.section_name}
                    </span>
                  )}
                  {conversation.script_name && (
                    <span className="conversation-chip">
                      <i className="fas fa-code mr-1"></i>
                      {conversation.script_name}
                    </span>
                  )}
                  {conversation.model && (
                    <span className="conversation-chip">
                      <i className="fas fa-brain mr-1"></i>
                      {conversation.model}
                    </span>
                  )}
                  <span className="conversation-chip">
                    <i className="fas fa-comment-dots mr-1"></i>
                    {conversation.message_count || 0}
                  </span>
                </div>
              </div>
            );
          })
        )}
      </div>

      {totalPages > 1 && (
        <Card.Footer className="bg-light py-2">
          <div className="d-flex justify-content-between align-items-center flex-wrap">
            <small className="text-muted">
              Page {currentPage} of {totalPages}
            </small>
            <Pagination size="sm" className="mb-0">
              <Pagination.First
                disabled={currentPage <= 1 || loading}
                onClick={() => onLoadPage(1)}
              />
              <Pagination.Prev
                disabled={currentPage <= 1 || loading}
                onClick={() => onLoadPage(currentPage - 1)}
              />
              <Pagination.Item active>{currentPage}</Pagination.Item>
              <Pagination.Next
                disabled={currentPage >= totalPages || loading}
                onClick={() => onLoadPage(currentPage + 1)}
              />
              <Pagination.Last
                disabled={currentPage >= totalPages || loading}
                onClick={() => onLoadPage(totalPages)}
              />
            </Pagination>
          </div>
        </Card.Footer>
      )}
    </Card>
  );
};
