/**
 * Conversation Type Classification
 * =================================
 *
 * Classifies conversations by their title prefix to determine origin
 * (user chat, prompt lab, builder, script, dataset import) and provides
 * display metadata (icon, badge, label) for the admin console.
 *
 * Conversations created by internal tools use bracket-prefixed titles
 * like "[Prompt Lab] Test run" or "[Script] Daily summary".
 *
 * @module components/admin/conversationTypes
 */

import type { AdminConversation } from '../../types';

/** Discriminated union of conversation origin types. */
export type ConversationTypeKey =
  | 'user'
  | 'prompt_lab'
  | 'prompt_builder'
  | 'dataset_import'
  | 'script'
  | 'unknown';

/** Display metadata for a conversation type, used for badges and icons. */
export interface ConversationTypeMeta {
  key: ConversationTypeKey;
  /** Human-readable label (e.g. "Prompt Lab", "Script") */
  label: string;
  /** FontAwesome icon class */
  icon: string;
  /** CSS class for the badge color */
  badgeClass: string;
  /** Whether the conversation was created by an automated tool */
  autogenerated: boolean;
  /** Cleaned title with bracket prefix removed */
  displayTitle: string;
}

const stripBracketPrefix = (title: string): string => title.replace(/^\[[^\]]+\]\s*/u, '').trim();

/**
 * Classify a conversation based on its title prefix and return display metadata.
 *
 * @param conversation - The conversation to classify
 * @returns Type metadata including label, icon, badge class, and cleaned title
 */
export const getConversationTypeMeta = (conversation: AdminConversation): ConversationTypeMeta => {
  const rawTitle = String(conversation.title || '').trim();
  const normalizedTitle = rawTitle.toLowerCase();

  if (normalizedTitle.startsWith('[prompt builder]')) {
    return {
      key: 'prompt_builder',
      label: 'Builder',
      icon: 'fa-magic',
      badgeClass: 'conversation-type-badge conversation-type-badge-builder',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Prompt builder run',
    };
  }

  if (normalizedTitle.startsWith('[prompt lab]')) {
    return {
      key: 'prompt_lab',
      label: 'Prompt Lab',
      icon: 'fa-flask',
      badgeClass: 'conversation-type-badge conversation-type-badge-prompt-lab',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Prompt lab run',
    };
  }

  if (normalizedTitle.startsWith('[dataset import parser]')) {
    return {
      key: 'dataset_import',
      label: 'Dataset Import',
      icon: 'fa-file-import',
      badgeClass: 'conversation-type-badge conversation-type-badge-dataset',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Dataset import parser',
    };
  }

  if (normalizedTitle.startsWith('[script]')) {
    return {
      key: 'script',
      label: 'Script',
      icon: 'fa-code',
      badgeClass: 'conversation-type-badge conversation-type-badge-script',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Script execution',
    };
  }

  if (rawTitle !== '') {
    return {
      key: 'user',
      label: 'Conversation',
      icon: 'fa-comments',
      badgeClass: 'conversation-type-badge conversation-type-badge-user',
      autogenerated: false,
      displayTitle: rawTitle,
    };
  }

  return {
    key: 'unknown',
    label: 'Conversation',
    icon: 'fa-comment',
    badgeClass: 'conversation-type-badge conversation-type-badge-unknown',
    autogenerated: false,
    displayTitle: 'Untitled Conversation',
  };
};

/** formatConversationDateBadge utility. */
export const formatConversationDateBadge = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
  });
};
