import type { AdminConversation } from '../../types';

export type ConversationTypeKey =
  | 'user'
  | 'prompt_lab'
  | 'prompt_builder'
  | 'dataset_import'
  | 'script'
  | 'unknown';

export interface ConversationTypeMeta {
  key: ConversationTypeKey;
  label: string;
  icon: string;
  badgeClass: string;
  autogenerated: boolean;
  displayTitle: string;
}

const stripBracketPrefix = (title: string): string => title.replace(/^\[[^\]]+\]\s*/u, '').trim();

export const getConversationTypeMeta = (conversation: AdminConversation): ConversationTypeMeta => {
  const rawTitle = String(conversation.title || '').trim();
  const normalizedTitle = rawTitle.toLowerCase();

  if (normalizedTitle.startsWith('[prompt builder]')) {
    return {
      key: 'prompt_builder',
      label: 'Builder',
      icon: 'fa-magic',
      badgeClass: 'conversation-type-badge conversation-type-badge-builder',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Prompt builder run',
    };
  }

  if (normalizedTitle.startsWith('[prompt lab]')) {
    return {
      key: 'prompt_lab',
      label: 'Prompt Lab',
      icon: 'fa-flask',
      badgeClass: 'conversation-type-badge conversation-type-badge-prompt-lab',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Prompt lab run',
    };
  }

  if (normalizedTitle.startsWith('[dataset import parser]')) {
    return {
      key: 'dataset_import',
      label: 'Dataset Import',
      icon: 'fa-file-import',
      badgeClass: 'conversation-type-badge conversation-type-badge-dataset',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Dataset import parser',
    };
  }

  if (normalizedTitle.startsWith('[script]')) {
    return {
      key: 'script',
      label: 'Script',
      icon: 'fa-code',
      badgeClass: 'conversation-type-badge conversation-type-badge-script',
      autogenerated: true,
      displayTitle: stripBracketPrefix(rawTitle) || 'Script execution',
    };
  }

  if (rawTitle !== '') {
    return {
      key: 'user',
      label: 'Conversation',
      icon: 'fa-comments',
      badgeClass: 'conversation-type-badge conversation-type-badge-user',
      autogenerated: false,
      displayTitle: rawTitle,
    };
  }

  return {
    key: 'unknown',
    label: 'Conversation',
    icon: 'fa-comment',
    badgeClass: 'conversation-type-badge conversation-type-badge-unknown',
    autogenerated: false,
    displayTitle: 'Untitled Conversation',
  };
};

export const formatConversationDateBadge = (dateString: string): string => {
  const date = new Date(dateString);
  return date.toLocaleDateString(undefined, {
    month: 'short',
    day: 'numeric',
  });
};
